---
# In order to have access to the other hosts defined in the 
# infrastructure, you want to esure you've accessed them all
- hosts: all
  tasks:
    - name: Load the cache / inventory
      ping: {}

- hosts: app
  tasks:
    - name: Clone the code
      git:
        repo={{ repo_url }}
        version={{ repo_version }}
        dest={{ repo_path }}
        accept_hostkey=yes
        force=yes

    # Other steps can be included: build the app, generate executable file, generate static files...

- hosts: web
  tasks:
    - name: Copy the static files to web folder
      command:
        rsync -av --delete {{ repo_path }}/static/ {{ webroot }}
