---
# In order to have access to the other hosts defined in the 
# infrastructure, you want to esure you've accessed them all
- hosts: all
  tasks:
    - name: Load the cache / inventory
      ping: {}

- hosts: app
  tasks:
    - name: Clone the code
      git:
        repo={{ repo_url }}
        version={{ repo_version }}
        dest={{ repo_path }}
        accept_hostkey=yes
        force=yes

    # Other steps can be included: build the app, generate executable file, generate static files...
    - name: Install app packages
      pip:
        requirements: "{{ repo_path }}/requirements.txt"

    - name: Create supervisor config
      template:
        src: app.conf.j2
        dest: /etc/supervisor/conf.d/app.conf

    - name: Restart the app
      supervisorctl:
        name: app
        state: restarted

- hosts: web
  tasks:
    - name: Copy the static files to web folder
      command:
        rsync -av --delete {{ repo_path }}/static/ {{ webroot }}
