- hosts: app
  tasks:
    - name: Load the inventory
      ping: {}

    - name: Clone the code
      git:
        repo={{ repo_url }}
        version={{ repo_version }}
        dest={{ repo_path }}
        accept_hostkey=yes
        force=yes

    - name: Install app packages
      pip:
        requirements: "{{ repo_path }}/requirements.txt"

    - name: Install supervisor
      apt:
        name: supervisor

    - name: Create supervisor config
      template:
        src: app.conf.j2
        dest: /etc/supervisor/conf.d/app.conf

    - name: Restart the app
      supervisorctl:
        name: app
        state: restarted

